[package]
name = "raymarch"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3

[build]
rustflags = ["-C", "target-cpu=native"]

[dependencies]
png = "0.17.10"

